---
- hosts: ubuntu
  gather_facts: true
  
  vars:
    jobids: []
  tasks:
  
    
    
    - name: task1
                
      ansible.builtin.command:
        sleep 7
      when: ansible_hostname == "ubuntu1"
      async: 10
      poll: 0
      register: result1

    - name: task2
      async: 10
      poll: 0
      register: result2
      ansible.builtin.command:
        sleep 7
      when: ansible_hostname == "ubuntu2"
    
    - name: task3
      async: 10
      poll: 0
      register: result3
      ansible.builtin.command:
        sleep 7
      when: ansible_hostname == "ubuntu3"

    - name:
      ansible.builtin.set_fact:
        jobids: >
                {% if item.ansible_job_id is defined -%}
                  {{ jobids + [item.ansible_job_id] }}
                {% else -%}
                  {{ jobids }}
                {% endif %}
       
      
      with_items: "{{ [ result1, result2, result3 ] }}"
    
    - name:
      ansible.builtin.debug:
        var: jobids

    - name:
      ansible.builtin.async_status:
        jid: "{{ item }}"
      with_items: "{{ jobids }}" 
      register: jobs_result
      until: jobs_result.finished   
      retries: 30

    
      
      
        
      

        
      

     

  
  